-- Oreste Utensils — launch catalog seed.
-- Generated from src/lib/seed.ts by scripts/generate-seed-sql.mjs — do not edit by hand.
-- Run after 0001_init.sql.

insert into public.ou_categories (name, slug, description, intro, image, sort_order) values
  ('Cookware', 'cookware', 'Pots, pans, dutch ovens and everything that touches the flame.', 'Buy quality cookware in Kigali — enamelled dutch ovens, stainless steel woks, cast-iron cocottes and stovetop kettles, hand-picked for Rwandan kitchens. Every piece is available at our City Plaza store or delivered across Kigali.', '/images/cat-cookware.webp', 1),
  ('Dinnerware', 'dinnerware', 'Stoneware, porcelain and ceramics for the table you gather around.', 'Shop dinnerware in Kigali — artisan stoneware dinner sets, ceramic serving bowls and porcelain mugs that turn everyday meals into occasions. See the full range at City Plaza or order for delivery anywhere in Kigali.', '/images/cat-dinnerware.webp', 2),
  ('Cutlery & Tools', 'cutlery', 'Forged knives, boards and the tools that do the real work.', 'Find professional kitchen knives and prep tools in Kigali — forged knife sets, acacia chopping boards and heat-resistant silicone utensils. The tools chefs actually reach for, now available in Rwanda.', '/images/cat-cutlery.webp', 3),
  ('Serveware & Glassware', 'serveware', 'Carafes, glasses and trays made for hosting.', 'Serveware and glassware in Kigali — glass carafes, wine glasses, whiskey tumblers and acacia serving trays for hosts who take their table seriously. Visit us at City Plaza or order online for Kigali delivery.', '/images/cat-serveware.webp', 4),
  ('Storage & Organisation', 'storage', 'Airtight jars and canisters that keep the pantry beautiful.', 'Kitchen storage solutions in Kigali — airtight glass jars and ceramic canister sets that keep ingredients fresh and shelves worth looking at. Available in-store at City Plaza and for delivery across Kigali.', '/images/cat-storage.webp', 5),
  ('Small Appliances', 'small-appliances', 'Blenders, pressure cookers and coffee gear that earn their counter space.', 'Shop small kitchen appliances in Kigali — countertop blenders, electric pressure cookers, drip coffee makers and burr grinders from trusted brands. Tested, warrantied and delivered across Kigali.', '/images/cat-small-appliances.webp', 6)
on conflict (slug) do nothing;

insert into public.ou_products (name, slug, category_slug, price_rwf, short_description, description, specs, images, featured, in_stock) values
  ('Ember Enamelled Dutch Oven — 5.2 L', 'ember-enamelled-dutch-oven', 'cookware', 145000, 'Heavy cast iron under a flame-orange enamel — sears, braises and bakes, then goes straight to the table.', 'The one pot that outlives trends. Ember''s cast-iron core holds heat evenly for deep, patient braises, while the enamelled interior needs no seasoning and cleans up with warm water. From slow-cooked isombe to Sunday bread, this is the workhorse your kitchen has been missing — and the enamel finish means it doubles as serveware.', '{"Capacity":"5.2 litres","Material":"Enamelled cast iron","Compatibility":"Gas, electric, induction, oven-safe to 250°C","Care":"Hand wash; no seasoning required"}'::jsonb, array['/products/ember-dutch-oven.webp', '/products/ember-dutch-oven-2.webp']::text[], true, true),
  ('Meridian Stainless Wok — 32 cm', 'meridian-stainless-wok', 'cookware', 89000, 'Tri-ply stainless steel with a fitted lid — high-heat stir-fries without the sticking.', 'A serious wok for serious heat. Meridian''s tri-ply construction sandwiches an aluminium core between stainless layers, so the base heats fast and even while the sides stay responsive. The fitted stainless lid turns it into a steamer or braiser, and riveted twin handles make the trip from stove to table a safe one.', '{"Diameter":"32 cm","Material":"Tri-ply stainless steel","Lid":"Fitted stainless steel","Compatibility":"All stovetops including induction"}'::jsonb, array['/products/meridian-stainless-wok.webp', '/products/meridian-stainless-wok-2.webp']::text[], true, true),
  ('Noir Cast-Iron Mini Cocotte — 0.6 L', 'noir-mini-cocotte', 'cookware', 48000, 'Single-serve cast iron for soups, baked eggs and desserts — oven to table in one piece.', 'Small pot, big presence. The Noir mini cocotte bakes, braises and serves individual portions with the same heat retention as a full dutch oven. Line up a row of them for dinner parties — soups stay hot at the table for twenty minutes, and the matte black finish looks the part.', '{"Capacity":"0.6 litres","Material":"Cast iron, matte enamel","Oven safe":"Up to 250°C","Serving":"Single portion"}'::jsonb, array['/products/noir-mini-cocotte.webp']::text[], false, true),
  ('Classic Stovetop Kettle — 2.5 L', 'classic-stovetop-kettle', 'cookware', 42000, 'Polished stainless kettle with a heat-shielded handle — icyayi the traditional way.', 'Some rituals deserve better hardware. This 2.5-litre stainless kettle brings water to a rolling boil on any stovetop and pours clean without dribbling. The wide base maximises contact with the flame, the handle stays cool, and the polished body will still look right in your kitchen a decade from now.', '{"Capacity":"2.5 litres","Material":"Polished stainless steel","Handle":"Heat-shielded steel","Compatibility":"Gas, electric, induction"}'::jsonb, array['/products/classic-stovetop-kettle.webp']::text[], false, true),
  ('Bamboo Steamer — 2 Tier, 25 cm', 'bamboo-steamer', 'cookware', 28000, 'Two-tier natural bamboo — steam vegetables, fish and dumplings without losing a single nutrient.', 'Steaming is the most honest way to cook, and bamboo does it best — it absorbs excess moisture so nothing turns soggy. Two stackable tiers let you steam a full meal at once over any pot or wok. Ideal for vegetables, sweet potatoes, fish and dumplings.', '{"Diameter":"25 cm","Tiers":"2 + lid","Material":"Natural bamboo","Care":"Rinse and air-dry; do not soak"}'::jsonb, array['/products/bamboo-steamer.webp']::text[], false, true),
  ('Artisan Stoneware Dinner Set — 12 Piece', 'artisan-stoneware-dinner-set', 'dinnerware', 185000, 'Hand-glazed stoneware for four — dinner plates, side plates and bowls with quietly imperfect edges.', 'Mass-produced plates all look the same because they are the same. This set is hand-glazed stoneware — each rim carries a slightly different pool of glaze, which is exactly the point. Four dinner plates, four side plates and four bowls, sturdy enough for daily use and considered enough for guests. Microwave and dishwasher safe.', '{"Pieces":"12 (serves 4)","Material":"Hand-glazed stoneware","Dinner plate":"27 cm","Care":"Dishwasher and microwave safe"}'::jsonb, array['/products/artisan-stoneware-dinner-set.webp']::text[], true, true),
  ('Duo Ceramic Serving Bowls', 'duo-ceramic-serving-bowls', 'dinnerware', 34000, 'A nesting pair of glazed ceramic bowls — patterned outside, food-safe glaze inside.', 'Two bowls that earn their shelf space. The smaller nests inside the larger, the hand-applied patterns make them serving pieces rather than just containers, and the interior glaze is food-safe and stain-resistant. Salads, fruit, ibirayi — they carry it all with some style.', '{"Set":"2 nesting bowls","Material":"Glazed ceramic","Sizes":"18 cm + 14 cm","Care":"Dishwasher safe"}'::jsonb, array['/products/duo-ceramic-serving-bowls.webp']::text[], false, true),
  ('Everyday Porcelain Mug — 350 ml', 'everyday-porcelain-mug', 'dinnerware', 12000, 'Clean white porcelain with a balanced handle — the mug you''ll reach for every single morning.', 'There''s always one mug everyone in the house fights over. This is that mug: 350 ml of bright white porcelain, walls thin enough to feel refined but thick enough to keep coffee hot, and a handle that fits actual fingers. Stackable, chip-resistant, endlessly replaceable — buy two.', '{"Capacity":"350 ml","Material":"White porcelain","Stackable":"Yes","Care":"Dishwasher and microwave safe"}'::jsonb, array['/products/everyday-porcelain-mug.webp']::text[], false, true),
  ('Barista Stoneware Mug — 300 ml', 'barista-stoneware-mug', 'dinnerware', 15000, 'Weighted stoneware with a matte glaze — built for slow coffee and strong Rwandan beans.', 'Made for coffee taken seriously. The thick stoneware walls hold temperature far longer than porcelain, the wide mouth lets espresso-based drinks breathe, and the matte glaze feels substantial in hand. If your beans come from Huye or Rulindo, they deserve this landing.', '{"Capacity":"300 ml","Material":"Matte-glazed stoneware","Heat retention":"High — thick walls","Care":"Dishwasher safe"}'::jsonb, array['/products/barista-stoneware-mug.webp']::text[], false, true),
  ('Forged 5-Piece Knife Set with Leather Roll', 'forged-knife-set', 'cutlery', 165000, 'High-carbon forged blades with pakkawood handles — chef''s, santoku, utility, carving fork and steel, in a leather roll.', 'The last knives you''ll buy for a long time. Each blade is forged from high-carbon stainless steel, hardened for edge retention and balanced against a full-tang pakkawood handle. The set covers every real job in a kitchen — chef''s knife, santoku, utility blade, carving fork and honing steel — and travels in a stitched leather roll that gets better with age.', '{"Pieces":"5 + leather roll","Steel":"High-carbon stainless, forged","Handles":"Full-tang pakkawood","Care":"Hand wash, hone weekly"}'::jsonb, array['/products/forged-knife-set.webp']::text[], true, true),
  ('Silicone Utensil Trio', 'silicone-utensil-trio', 'cutlery', 22000, 'Three heat-resistant silicone spoons that won''t scratch your non-stick pans — ever.', 'Metal utensils are how non-stick pans die. This trio of solid-core silicone spoons is heat-resistant to 230°C, gentle on every coating you own, and rigid enough to actually stir a thick pot of ibihaza. Dishwasher safe, stain-resistant, and the colours survive years of use.', '{"Pieces":"3 spoons","Material":"Solid-core food-grade silicone","Heat resistance":"230°C","Care":"Dishwasher safe"}'::jsonb, array['/products/silicone-utensil-trio.webp']::text[], false, true),
  ('Acacia Board Set — 2 Boards + Crock', 'acacia-board-set', 'cutlery', 38000, 'Two solid acacia boards and a ceramic utensil crock — the prep station, sorted.', 'Acacia is dense enough to shrug off knife marks and handsome enough to serve from. This set pairs a large prep board with a smaller bar board, plus a ceramic crock to keep your most-used utensils standing by the stove. Oil them every few months and they''ll outlast the kitchen.', '{"Set":"2 boards + ceramic crock","Material":"Solid acacia wood","Large board":"40 × 28 cm","Care":"Hand wash, oil monthly"}'::jsonb, array['/products/acacia-board-set.webp', '/products/acacia-board-set-2.webp']::text[], false, true),
  ('Glass Carafe & Tumbler Set', 'glass-carafe-set', 'serveware', 45000, 'A 1.2 L pouring carafe with matching tumblers — water, juice or milk, served properly.', 'The difference between putting a plastic bottle on the table and pouring from glass is the difference between feeding people and hosting them. This carafe pours clean from a precision lip, the tumblers stack, and everything is dishwasher safe. Breakfast juice to bedside water — one set, every occasion.', '{"Carafe":"1.2 litres","Tumblers":"4 × 300 ml","Material":"Lead-free glass","Care":"Dishwasher safe"}'::jsonb, array['/products/glass-carafe-set.webp']::text[], false, true),
  ('Highball Glasses — Set of 6', 'highball-glasses', 'serveware', 32000, 'Six tall, heavy-based highballs — for iced tea, juice and long drinks that need room for ice.', 'A proper highball is tall enough for ice to do its job and heavy enough at the base to feel like it belongs in your hand. These six are made from clarified glass that stays brilliant through hundreds of dishwasher cycles. The everyday glass, upgraded.', '{"Set":"6 glasses","Capacity":"350 ml each","Material":"Clarified glass, weighted base","Care":"Dishwasher safe"}'::jsonb, array['/products/highball-glasses.webp']::text[], false, true),
  ('Whiskey Tumblers — Set of 4', 'whiskey-tumblers', 'serveware', 38000, 'Four heavy-bottomed rocks glasses with a faceted base that catches the light.', 'For the drinks you don''t rush. These rocks glasses carry serious weight in the base — faceted so they throw light across the table — with a wide mouth that lets whatever you''re pouring open up. Equally at home with a single large ice cube or a strong tonic.', '{"Set":"4 glasses","Capacity":"300 ml each","Material":"Heavy-bottomed clarified glass","Care":"Dishwasher safe"}'::jsonb, array['/products/whiskey-tumblers.webp']::text[], false, true),
  ('Stemmed Wine Glasses — Set of 6', 'stemmed-wine-glasses', 'serveware', 54000, 'Six fine-rimmed, laser-cut stemmed glasses — the universal shape that flatters every bottle.', 'One shape, every wine. These universal glasses have a laser-cut rim with no rolled lip — wine flows onto the palate instead of dropping — and a bowl proportioned to concentrate aromas whether you''re pouring red, white or rosé. The stems are pulled, not joined, so there''s no weak seam.', '{"Set":"6 glasses","Capacity":"450 ml each","Rim":"Laser-cut, no rolled lip","Care":"Hand wash recommended"}'::jsonb, array['/products/stemmed-wine-glasses.webp', '/products/stemmed-wine-glasses-2.webp']::text[], false, true),
  ('Acacia Serving Tray & Bowl Set', 'acacia-serving-tray', 'serveware', 58000, 'A carved acacia tray with two matching bowls — fruit, snacks or the full grazing spread.', 'Carved from single pieces of acacia, this tray-and-bowls set does the quiet work of making everything placed on it look intentional. Deep enough for fruit, wide enough for a full spread of snacks when guests arrive. The grain on every piece is one of one.', '{"Set":"1 tray + 2 bowls","Material":"Solid carved acacia","Tray":"45 × 25 cm","Care":"Wipe clean, oil occasionally"}'::jsonb, array['/products/acacia-serving-tray.webp']::text[], false, true),
  ('Airtight Glass Jar — 1 L', 'airtight-glass-jar', 'storage', 9500, 'Screw-top clarity for rice, beans, spices and flour — see what you have, keep it fresh.', 'The pantry upgrade that costs less than lunch. A silicone-sealed screw lid keeps moisture and weevils out of rice, beans, flour and sugar, while the clear glass means you never buy a third bag of something you already had two of. Buy several — they line up beautifully.', '{"Capacity":"1 litre","Material":"Glass, steel lid, silicone seal","Seal":"Airtight screw-top","Care":"Dishwasher safe (lid hand wash)"}'::jsonb, array['/products/airtight-glass-jar.webp']::text[], false, true),
  ('Atelier Ceramic Canister Set', 'atelier-canister-set', 'storage', 65000, 'Speckled two-tone ceramic canisters — coffee, sugar and tea storage that deserves the counter.', 'Storage you don''t have to hide. Each Atelier canister is glazed in a two-tone speckled finish with an unglazed base band — the kind of piece that usually lives in design stores at triple the price. Keep coffee, sugar and tea within arm''s reach and on display.', '{"Set":"4 canisters, mixed sizes","Material":"Two-tone glazed ceramic","Finish":"Speckled, unglazed base band","Care":"Wipe clean"}'::jsonb, array['/products/atelier-canister-set.webp']::text[], true, true),
  ('Pro Countertop Blender — 1.5 L', 'pro-countertop-blender', 'small-appliances', 95000, '1000 W motor, hardened blades and a 1.5 L glass jug — smoothies, sauces and ibinyomoro juice in seconds.', 'A blender either powers through or it doesn''t. This one does: a 1000-watt motor spins hardened stainless blades fast enough to turn whole fruit, ice and greens into a genuinely smooth blend — no chunks, no stalling. The glass jug won''t stain or hold odours like plastic, and the base wipes clean in seconds.', '{"Motor":"1000 W","Jug":"1.5 L glass","Blades":"6-point hardened stainless","Speeds":"3 + pulse"}'::jsonb, array['/products/pro-countertop-blender.webp']::text[], true, true),
  ('8-in-1 Electric Pressure Cooker — 6 L', 'electric-pressure-cooker', 'small-appliances', 135000, 'Pressure cook, slow cook, steam, sauté and more — beans in 30 minutes instead of 3 hours.', 'The appliance that changes how a Rwandan kitchen runs. Dry beans go from bag to table in half an hour. Rice cooks itself while you handle everything else. Eight programmes cover pressure cooking, slow cooking, steaming, sautéing and warming, with ten safety mechanisms standing guard. Less charcoal, less gas, less waiting.', '{"Capacity":"6 litres","Programmes":"8 cooking modes","Safety":"10 protection mechanisms","Power":"1000 W"}'::jsonb, array['/products/electric-pressure-cooker.webp']::text[], false, true),
  ('Drip Coffee Maker — 10 Cup', 'drip-coffee-maker', 'small-appliances', 78000, 'Precision-temperature brewing with a glass carafe — do justice to Rwandan coffee at home.', 'Rwanda grows some of the best coffee on earth; most of it gets brewed badly. This machine holds water at the correct extraction temperature and showers it evenly over the grounds — the two things cheap coffee makers never do. Ten cups per brew, a warming plate that doesn''t scorch, and a carafe that pours clean.', '{"Capacity":"10 cups / 1.25 L","Brew temp":"92–96°C regulated","Carafe":"Glass with warming plate","Filter":"Reusable + paper compatible"}'::jsonb, array['/products/drip-coffee-maker.webp']::text[], false, true),
  ('Precision Burr Coffee Grinder', 'burr-coffee-grinder', 'small-appliances', 88000, 'Conical steel burrs with 40 grind settings — from French press to espresso-fine.', 'Ground coffee starts dying the moment it''s ground — which is why serious coffee people grind at home. Conical steel burrs crush beans uniformly instead of shattering them like blade grinders do, and 40 settings take you from coarse French press to espresso-fine. Pairs with our drip machine for the full home-café setup.', '{"Burrs":"Conical hardened steel","Settings":"40 grind sizes","Hopper":"250 g beans","Timer":"Dose-by-seconds dial"}'::jsonb, array['/products/burr-coffee-grinder.webp']::text[], false, false)
on conflict (slug) do nothing;
